COUNTRY_CODES = {
	'Albania': 'AL',
	'Algeria': 'DZ',
	'Andorra': 'AD',
	'Argentina': 'AR',
	'Armenia': 'AM',
	'Australia': 'AU',
	'Austria': 'AT',
	'Azerbaijan': 'AZ',
	'Bahrain': 'BH',
	'Bangladesh': 'BD',
	'Belarus': 'BY',
	'Belgium': 'BE',
	'Bolivia': 'BO',
	'Bosnia and Herzegovina': 'BA',
	'Brazil': 'BR',
	'Brunei': 'BN',
	'Bulgaria': 'BG',
	'Cambodia': 'KH',
	'Canada': 'CA',
	'Chile': 'CL',
	'China': 'CN',
	'Colombia': 'CO',
	'Costa Rica': 'CR',
	'Croatia': 'HR',
	'Cuba': 'CU',
	'Cyprus': 'CY',
	'Czech Republic': 'CZ',
	'Czechia': 'CZ',
	'Denmark': 'DK',
	'Dominican Republic': 'DO',
	'Ecuador': 'EC',
	'Egypt': 'EG',
	'El Salvador': 'SV',
	'Estonia': 'EE',
	'Fiji': 'FJ',
	'Finland': 'FI',
	'France': 'FR',
	'Georgia': 'GE',
	'Germany': 'DE',
	'Ghana': 'GH',
	'Great Britain': 'GB',
	'Greece': 'GR',
	'Guatemala': 'GT',
	'Honduras': 'HN',
	'Hong Kong': 'HK',
	'Hungary': 'HU',
	'Iceland': 'IS',
	'India': 'IN',
	'Indonesia': 'ID',
	'Iran': 'IR',
	'Iraq': 'IQ',
	'Ireland': 'IE',
	'Israel': 'IL',
	'Italy': 'IT',
	'Jamaica': 'JM',
	'Japan': 'JP',
	'Jordan': 'JO',
	'Kazakhstan': 'KZ',
	'Kenya': 'KE',
	'Korea, Republic of': 'KR',
	'Kuwait': 'KW',
	'Kyrgyzstan': 'KG',
	'Laos': 'LA',
	'Latvia': 'LV',
	'Lebanon': 'LB',
	'Liechtenstein': 'LI',
	'Lithuania': 'LT',
	'Luxembourg': 'LU',
	'Macedonia': 'MK',
	'Malaysia': 'MY',
	'Malta': 'MT',
	'Mexico': 'MX',
	'Moldova': 'MD',
	'Monaco': 'MC',
	'Mongolia': 'MN',
	'Montenegro': 'ME',
	'Morocco': 'MA',
	'Myanmar': 'MM',
	'Nepal': 'NP',
	'Netherlands': 'NL',
	'New Zealand': 'NZ',
	'Nicaragua': 'NI',
	'Nigeria': 'NG',
	'North Macedonia': 'MK',
	'Norway': 'NO',
	'Oman': 'OM',
	'Pakistan': 'PK',
	'Panama': 'PA',
	'Papua New Guinea': 'PG',
	'Paraguay': 'PY',
	'Peru': 'PE',
	'Philippines': 'PH',
	'Poland': 'PL',
	'Portugal': 'PT',
	'Puerto Rico': 'PR',
	'Qatar': 'QA',
	'Romania': 'RO',
	'Russia': 'RU',
	'Russian Federation': 'RU',
	'Samoa': 'WS',
	'San Marino': 'SM',
	'Saudi Arabia': 'SA',
	'Serbia': 'RS',
	'Singapore': 'SG',
	'Slovakia': 'SK',
	'Slovenia': 'SI',
	'Solomon Islands': 'SB',
	'South Africa': 'ZA',
	'South Korea': 'KR',
	'Spain': 'ES',
	'Sri Lanka': 'LK',
	'Sweden': 'SE',
	'Switzerland': 'CH',
	'Taiwan': 'TW',
	'Tajikistan': 'TJ',
	'Thailand': 'TH',
	'The Netherlands': 'NL',
	'Timor-Leste': 'TL',
	'Tonga': 'TO',
	'Tunisia': 'TN',
	'Turkiye': 'TR',
	'Turkmenistan': 'TM',
	'UK': 'GB',
	'Ukraine': 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom': 'GB',
	'United States': 'US',
	'Uruguay': 'UY',
	'USA': 'US',
	'Uzbekistan': 'UZ',
	'Vanuatu': 'VU',
	'Vatican City': 'VA',
	'Venezuela': 'VE',
	'Vietnam': 'VN',
}
