COUNTRY_CODES = {
	'Aaland Islands': 'AX',
	'Albania': 'AL',
	'Algeria': 'DZ',
	'American Samoa': 'AS',
	'Andorra': 'AD',
	'Anguilla': 'AI',
	'Antigua and Barbuda': 'AG',
	'Argentina Republic': 'AR',
	'Armenia': 'AM',
	'Aruba': 'AW',
	'Ascension Island': 'AC',
	'Australia': 'AU',
	'Austria': 'AT',
	'Azerbaijan': 'AZ',
	'Bahamas': 'BS',
	'Bahrain': 'BH',
	'Bangladesh': 'BD',
	'Barbados': 'BB',
	'Belarus': 'BY',
	'Belgium': 'BE',
	'Belize': 'BZ',
	'Bermuda': 'BM',
	'Bolivia': 'BO',
	'Bonaire': 'BQ',
	'Bosnia and Hercegovina': 'BA',
	'Bosnia and Herzegovina': 'BA',
	'Botswana': 'BW',
	'Brazil': 'BR',
	'British Virgin Islands': 'VG',
	'Brunei Darussalam': 'BN',
	'Bulgaria': 'BG',
	'Burkina Faso': 'BF',
	'Cambodia': 'KH',
	'Cameroon': 'CM',
	'Canada': 'CA',
	'Cape Verde': 'CV',
	'Cayman Islands': 'KY',
	'Central African Republic': 'CF',
	'Chad': 'TD',
	'Chile': 'CL',
	'China': 'CN',
	'Colombia': 'CO',
	'Cook Islands': 'CK',
	'Corsica': 'FR',
	'Costa Rica': 'CR',
	'Croatia': 'HR',
	'Cuba': 'CU',
	'Curacao': 'CW',
	'Cyprus': 'CY',
	'Czech Republic': 'CZ',
	'Czechia': 'CZ',
	'Denmark': 'DK',
	'Djibouti': 'DJ',
	'Dominica': 'DM',
	'Dominican Republic': 'DO',
	'Ecuador': 'EC',
	'Egypt': 'EG',
	'El Salvador': 'SV',
	'Equatorial Guinea': 'GQ',
	'Estonia': 'EE',
	'Falkland Islands': 'FK',
	'Faroe Islands': 'FO',
	'Fiji': 'FJ',
	'Finland': 'FI',
	'France': 'FR',
	'French Guiana': 'GF',
	'Georgia': 'GE',
	'Germany': 'DE',
	'Ghana': 'GH',
	'Gibraltar': 'GI',
	'Great Britain': 'GB',
	'Greece': 'GR',
	'Greenland': 'GL',
	'Grenada': 'GD',
	'Guadeloupe': 'GP',
	'Guam': 'GU',
	'Guatemala': 'GT',
	'Guinea': 'GN',
	'Guyana': 'GY',
	'Haiti': 'HT',
	'Honduras': 'HN',
	'Hong Kong': 'HK',
	'Hungary': 'HU',
	'Iceland': 'IS',
	'India': 'IN',
	'Indonesia': 'ID',
	'Iran': 'IR',
	'Iraq': 'IQ',
	'Ireland': 'IE',
	'Israel': 'IL',
	'Italy': 'IT',
	'Ivory Coast': 'CI',
	'Jamaica': 'JM',
	'Japan': 'JP',
	'Jordan': 'JO',
	'Kazakhstan': 'KZ',
	'Kenya': 'KE',
	'Korea Republic of': 'KR',
	'Korea S, Republic of': 'KR',
	'Kosovo': 'XK',
	'Kuwait': 'KW',
	'Kyrgyzstan': 'KG',
	'Laos': 'LA',
	'Latvia': 'LV',
	'Lebanon': 'LB',
	'Lesotho': 'LS',
	'Liberia': 'LR',
	'Liechtenstein': 'LI',
	'Lithuania': 'LT',
	'Luxembourg': 'LU',
	'Luxemburg': 'LU',
	'Macao': 'MO',
	'Macedonia': 'MK',
	'Madagascar': 'MG',
	'Malawi': 'MW',
	'Malaysia': 'MY',
	'Maldives': 'MV',
	'Malta': 'MT',
	'Martinique': 'MQ',
	'Mauretania': 'MR',
	'Mauritius': 'MU',
	'Mexico': 'MX',
	'Micronesia': 'FM',
	'Moldova': 'MD',
	'Monaco': 'MC',
	'Mongolia': 'MN',
	'Montenegro': 'ME',
	'Montserrat': 'MS',
	'Morocco': 'MA',
	'Mozambique': 'MZ',
	'Myanmar': 'MM',
	'Namibia': 'NA',
	'Nepal': 'NP',
	'Netherlands': 'NL',
	'New Caledonia': 'NC',
	'New Zealand': 'NZ',
	'Nicaragua': 'NI',
	'Nigeria': 'NG',
	'Norway': 'NO',
	'Oman': 'OM',
	'Pakistan': 'PK',
	'Palau': 'PW',
	'Panama': 'PA',
	'Papua New Guinea': 'PG',
	'Paraguay': 'PY',
	'Peru': 'PE',
	'Philippines': 'PH',
	'Poland': 'PL',
	'Portugal': 'PT',
	'Puerto Rico': 'PR',
	'Qatar': 'QA',
	'Reunion': 'RE',
	'Romania': 'RO',
	'Russia': 'RU',
	'Saint Kitts and Nevis': 'KN',
	'Saint Lucia': 'LC',
	'Saint Vincent and the Grenadines': 'VC',
	'Samoa': 'WS',
	'San Marino': 'SM',
	'Saudi Arabia': 'SA',
	'Senegal': 'SN',
	'Serbia': 'RS',
	'Seychelles': 'SC',
	'Singapore': 'SG',
	'Slovakia': 'SK',
	'Slovenia': 'SI',
	'Solomon Islands': 'SB',
	'South Africa': 'ZA',
	'Spain': 'ES',
	'Sri Lanka': 'LK',
	'Sudan': 'SD',
	'Suriname': 'SR',
	'Swasiland': 'SZ',
	'Sweden': 'SE',
	'Switzerland': 'CH',
	'Taiwan': 'TW',
	'Tajikistan': 'TJ',
	'Tanzania': 'TZ',
	'Thailand': 'TH',
	'Timor-Leste': 'TL',
	'Togo': 'TG',
	'Tonga': 'TO',
	'Trinidad and Tobago': 'TT',
	'Tunisia': 'TN',
	'Turkey': 'TR',
	'Turkiye': 'TR',
	'Turkmenistan': 'TM',
	'Trkiye': 'TR',
	'U.S. Virgin Islands': 'VI',
	'UK': 'GB',
	'Ukraine': 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom': 'GB',
	'United States': 'US',
	'Uruguay': 'UY',
	'USA': 'US',
	'Uzbekistan': 'UZ',
	'Vanuatu': 'VU',
	'Vatican City': 'VA',
	'Venezuela': 'VE',
	'Vietnam': 'VN',
	'Yemen': 'YE',
	'Zambia': 'ZM',
	'Zimbabwe': 'ZW',
}
